apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: query-power-metrics-task
spec:
  workspaces:
    - name: source
      description: The workspace containing the git repository.
  params:
    - name: prometheus-url
      description: The URL of the Prometheus server
      type: string
    - name: app-name
      description: The name of the application to query for.
      type: string
      default: "hello-go-app"
    - name: app-namespace
      description: The namespace of the application.
      type: string
  steps:
    - name: query-power-metrics
      image: registry.access.redhat.com/ubi8/python-39
      script: |
        #!/bin/bash
        set -e

        echo "Installing oc CLI..."
        curl -LO https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        tar -xf openshift-client-linux.tar.gz
        mv oc /usr/local/bin/
        rm kubectl README.md openshift-client-linux.tar.gz
        echo "oc CLI installed."

        pip install prometheus-api-client
        
        export PROMETHEUS_URL=$(params.prometheus-url)
        # This assumes the task is running in a pod with a service account that has permissions to get pods
        export PROMETHEUS_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        export TARGET_POD_NAME=$(oc get pods -n $(params.app-namespace) -l app=$(params.app-name) -o jsonpath='{.items[0].metadata.name}')
        export TARGET_NAMESPACE=$(params.app-namespace)
        export TARGET_CONTAINER_NAME=$(params.app-name)

        python $(workspaces.source.path)/scripts/query-power-metrics.py

      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory 